### ISSUE TITLE
Plugin not showing in plugin list or preferences screen

### ISSUE THREAD

**Issue by Caffe1neAdd1ct** [lotan/rhythmbox-ampache#1]
Hi lotan,

If you have time i'm having issues getting your re-written plugin to work with rhythmbox version 3.0.2.

Installed via 
git clone https://repo
sudo python setup.py install 

Fired up rhythmbox and can't see the plugin in the list to enable and no options in the preferences area.

Debug info:

$ rhythmbox -D ampache

(rhythmbox:21440): GLib-GObject-CRITICAL **: Custom constructor for class SoupServer returned NULL (which is invalid).  Unable to remove object from construction_objects list, so memory was probably just leaked.  Please use GInitable instead.

(rhythmbox:21440): Gtk-WARNING **: mnemonic "s" wasn't removed for widget (0xa5adb0)

Any help would be great :+1:

**Comment by lachlan-00** [comment]
Is rb.find_plugin_file hardcoded to /usr/share/rhythmbox/plugins/ or if you install to the local user plugin folder can it find them there? (doesn't seem to find them unless i put them in /usr)

setup.py it doesn't seem to actually do that though. I had to make the folder in /usr and then copy the plugin to my local plugin folder to get it to find the ui and open preferences.

**Comment by lotan** [comment]
The basis for rhythmbox plugins is libpeas.

Judging from these:

https://github.com/GNOME/libpeas/blob/f4d5f941e7003c1cb05d601ed50ab98a182579dc/libpeas/peas-plugin-info.c#L266
https://github.com/GNOME/libpeas/blob/f4d5f941e7003c1cb05d601ed50ab98a182579dc/libpeas/Makefile.am#L11

I'd say, it's hardcoded depending on how libpeas was built, typically /usr/share.

What I didn't get from your comment, if you have discovered an actual mistake that needs correcting.
If so, please could you let me know? Thank you!

**Comment by lachlan-00** [comment]
I think it might be a bug in setup.py line 40?

With the default setup.py files get installed to /usr/local/share/rhythmbox/plugins/ampache (which must be why @Caffe1neAdd1ct and i had this problem.)

If i add the base directory instead it will install in the correct location.
("/usr/share/rhythmbox/plugins/ampache", ["ampache-prefs.ui", "ampache.ico", "ampache.png"]),

Not sure why it ignores /usr/local when searching?

**Comment by lotan** [comment]
I wouldn't recommend your substitution.
While I freely admit I'm no expert in the inner workings of python module installation, it seems to me that yours is a prefix problem.

According to

   https://docs.python.org/2/install/#how-installation-works

the installation prefix on a linux platform is usually determined by the way python was installed. A package installation usually defaults to ```/usr``` and a user compiled version defaults to ```/usr/local```.

I assume you either have an unusual case or have compiled your own python platform.

In order to use the ```setup.py``` installation as intended I would suggest adding the arguments ```--prefix``` and ```--exec-prefix``` as described in

   https://docs.python.org/2/install/#alternate-installation

**Comment by moretocome** [comment]
I had to do:
```
sudo ln -s /usr/local/lib64/rhythmbox/plugins/ampache /usr/lib/rhythmbox/plugins/

sudo ln -s /usr/local/share/rhythmbox/plugins/ampache /usr/share/rhythmbox/plugins/
```
to be able to load the plugin in Linux Mint 18.3 with Rhythembox installed from the Software Manager.

**Comment by lotan** [comment]
@moretocome: if the distribution packet doesn't work for you, you best address that to the package maintainer. Also tell them that dependencies are missing, judging from your other issue comment.

**Comment by SDAdham** [comment]
I've followed the steps `sudo python setup.py install --prefix /usr --exec-prefix /usr` but still it's not showing up in the rhythmbox plugins, i'm using ubuntu 18.04, is this plugin still maintained?

**Comment by lotan** [comment]
@SDAdham: First of all, I'm sorry that your distribution maintainer doesn't prepare a package that has solved all the installation issues.

The setup.py tries to guess where the rhythmbox-ampache files have to go on your distribution but as you can see in the issues: it fails at times.

Possible solution: Manual installation.

There are three paths to consider and depending on your architecture they may be different:
* Rhythmbox's lib path (e.g. ```/usr/lib64/rhythmbox```)
* Rhythmbox's share path (e.g. ```/usr/share/rhythmbox```)
* glib's schema path (e.g. ```/usr/share/glib-2.0/schemas```)

Find each of the relevant paths in your system.

The first two each have a plugins folder. Each of those plugins folders should contain a folder names ```ampache```.

```<rhythmbox_lib>/plugins/ampache``` should contain the files ```ampache.plugin```, ```ampache.py```, ```AmpacheBrowser.py```, ```AmpacheConfigDialog.py```.
```<rhythmbox_share>/plugins/ampache``` should contain the files ```ampache-prefs.ui```, ```ampache.ico```, ```ampache.png```.
Finally ```<schemas>``` should contain ```org.gnome.rhythmbox.plugins.ampache.gschema.xml```.

Ensure that all these files are available. Finally, execute
```glib-compile-schemas /usr/share/glib-2.0/schemas``` to compile the schema.

If that has all been done and rhythmbox still doesn't appear, please post relevant excerpts of ```rhythmbox -d``` and ```rhythmbox -D ampache```.

**Comment by SDAdham** [comment]
@lotan thx for the response, I followed the manual installation, and everything was in place already, I executed `glib-compile-schemas /usr/share/glib-2.0/schemas` and no output, seems successfully to me (but I had to run it with `sudo`)

Still no plugin, I started rhythmbox with the debug flags but no ampache in the logs, the logs are too huge due to my music library is too full but no keyword for `ampache`, in regards to the `-D`, that's the only output:
```
(rhythmbox:20687): GLib-CRITICAL **: 21:20:32.191: g_key_file_load_from_file: assertion 'file != NULL' failed
```
Just so I be sure about it, the plugin name should be `ampache`, right?

**Comment by lotan** [comment]
@SDAdham: Well, in the Plugins list, its name is 'Ampache Library'.
But if all files are in the right place, I'm at a loss how to proceed. Are there other plugins installed in the lib and share locations?
I believe in Ubuntu, you can list the files of a package using

```apt-file list rhythmbox```

Can you ensure the lib and share paths are in accordance with the ones you identified?

**Comment by SDAdham** [comment]
Yes, I agree, I am also lost:
```
$ apt-file list rhythmbox
rhythmbox: /usr/bin/rhythmbox
rhythmbox: /usr/bin/rhythmbox-client
rhythmbox: /usr/lib/mime/packages/rhythmbox
rhythmbox: /usr/lib/rhythmbox/rhythmbox-metadata
rhythmbox: /usr/share/appdata/rhythmbox.appdata.xml
rhythmbox: /usr/share/applications/rhythmbox-device.desktop
rhythmbox: /usr/share/applications/rhythmbox.desktop
rhythmbox: /usr/share/doc/rhythmbox/AUTHORS
rhythmbox: /usr/share/doc/rhythmbox/NEWS.gz
rhythmbox: /usr/share/doc/rhythmbox/README
rhythmbox: /usr/share/doc/rhythmbox/README.Debian
rhythmbox: /usr/share/doc/rhythmbox/THANKS
rhythmbox: /usr/share/doc/rhythmbox/TODO.Debian
rhythmbox: /usr/share/doc/rhythmbox/changelog.Debian.gz
rhythmbox: /usr/share/doc/rhythmbox/copyright
rhythmbox: /usr/share/man/man1/rhythmbox-client.1.gz
rhythmbox: /usr/share/man/man1/rhythmbox.1.gz
```

**Comment by lotan** [comment]
According to this

   https://packages.ubuntu.com/bionic/amd64/rhythmbox-plugins/filelist

the library folder on amd64 architecture seems to be

   ```/usr/lib/x86_64-linux-gnu/rhythmbox```

**Comment by lotan** [comment]
Strange...
But if it works, I won't complain.
