### ISSUE TITLE
g-io-error-quark: Operation not supported (15)

### ISSUE THREAD

**Issue by tilal6991** [lotan/rhythmbox-ampache#11]
When I attempt to open the Ampache library in Rhythmbox, I get the above error popping up in a dialog box. I also see the following line in the debug log:
`
(06:01:46) [0x125cf60] [AmpacheBrowser.update] /usr/lib/rhythmbox/plugins/ampache/AmpacheBrowser.py:922: downloading handshake: localhost/server/xml.server.php?action=handshake&auth=AUTH&timestamp=1467867706&user=USER&version=350001
`

The only special thing I can see that I'm doing is that I'm SSH port forwarding to localhost an instance hosted on my server. Unless I need to forward some other port than 80 I can't see this being a problem though.

**Comment by lotan** [comment]
Your server URI is wrong. Instead of ```localhost``` you have to use a full URI, like ```http://localhost``` and I suspect your you have installed Ampache to a specific path, like ```http://localhost/ampache```.

**Comment by tilal6991** [comment]
I actually have it installed on root but I was indeed missing the http:// part. Thanks for the hint!
