### ISSUE TITLE
Only song whose titles start with letters from A to F are being shown

### ISSUE THREAD

**Issue by roobre** [lotan/rhythmbox-ampache#12]
I have over 5k songs on my Ampache library, all of them accesible and playable from the WebUI. However, only the first 1800 are shown on the extension main menu, as well as in playlists.

I've checked the XML files in the .cache directory, and they appear to be complete and hold all the songs in my ampache library.

```
[roobre@Archpv3]% ~> grep -e 'song id' .cache/rhythmbox/ampache/_songs.xml -c
5080
```

In rhythmbox, up to letter F they are listed correctly. From that, it jumps to special characters and such:

![deepinscreenshot20161202151201](https://cloud.githubusercontent.com/assets/969721/20836900/cb86ebd4-b8a1-11e6-81de-bf2ac254e748.png)

Maybe some logs would help, if you tell me how to get them, I'll attach them here.

Best regards, and thanks in advance for your time and work o/

**Comment by lotan** [comment]
Generally, if you want to receive log data for a specific subsystem or plugin, use ```rhythmbox -D <pattern>```. In this case ```rhythmbox -D ampache```. If you want to receive all log data, use ```rhythmbox -d```.
If the songs cache contains all the songs I doubt that the plugin logs will help you much.
As it seems, rhythmbox is able to process the songs in alphabetical order, can you tell which song is the last one that got processed and predict the song that is problematic (using the _songs.xml cache file)?
If you can identify this song, look for suspicious characteristics. Special characters come to mind.

**Comment by roobre** [comment]
Hello,

Thanks for the hint on the debug params! With that info I traced the error to certain sons which had weird characters on their id3 tags.

It's fixed now, thank you 👍
