### ISSUE TITLE
Rhythmbox crashes while "downloading _songs" from nextcloud-music app ampache endpoint

### ISSUE THREAD

**Issue by danieldemus** [lotan/rhythmbox-ampache#17]

**Comment by lotan** [comment]
Can you please provide more information?

Start Rhythmbox on the command line by executing

```rhythmbox -d```

or specifically

```rhythmbox -D ampache```

and post the result.

**Comment by jlombs** [comment]
@lotan, I can confirm this on Nextcloud 13.0.1 with the music app as well.

My output of `rhythmbox -D ampache` is the following: 
 
`(rhythmbox:22331): RhythmDB-WARNING **: Unable to convert new value for property track-number from gchararray to gulong`
`**` 
`RhythmDB:ERROR:rhythmdb.c:3485:rhythmdb_entry_set_internal: code should not be reached`
`Aborted (core dumped)`

**Comment by lotan** [comment]
@jlombs: At first glance this looks like the songinformation from Nextclound may contain non-numeric characters for tracknumber and rhythmbox is choking on it.
You can check by downloading the URIs that you can see during ```rhythmbox -D ampache``` independently through a browser and checking the ```<track/>``` tags for invalid (non-numeric) entries.
If you put that data somewhere I can access, I'm happy to help looking.

**Comment by danieldemus** [comment]
I listen to a newspaper where each article is supposed to have a tracknumber/tracktotal. Whatever system they use to generate tracknumber/tracktotal is what could generously be called "patchy". Not all tracks have any values in the fields, while in some rare cases there is non-numeric content.
Powerampache seems to be able to handle these. You could assume 0 for tracknumber.

**Comment by lotan** [comment]
@danieldemus Thanks for getting back so quickly!

**Comment by jlombs** [comment]
The fix solved this issue for me as well.

Thanks!
