### ISSUE TITLE
Secure Connection Setup Failed

### ISSUE THREAD

**Issue by jlombs** [lotan/rhythmbox-ampache#18]
Although I can connect and see my library through the ampache plug-in, my tracks won't play. They throw a "Playback Error: Secure connection setup failed." message.

Running `rhythmbox -d ampache` produces the following relevant messages when I attempt to play a song:

`(08:27:38) [0x7f0d38005840] [state_change_finished] rb-player-gst.c:445: setting new playback URI https://192.168.0.46/nextcloud/apps/music/ampache/server/xml.server.php?action=play&filter=1&auth=47749254abba0ec16b4907080e8e3bb8`
`(08:27:38) [0x7f0d38005840] [start_state_change] rb-player-gst.c:406: changing state to PLAYING`
`(08:27:38) [0x7f0d38005840] [rb_shell_player_set_playing_entry] rb-shell-player.c:880: Success!`
`(08:27:38) [0x7f0d38005840] [bus_cb] rb-player-gst.c:531: got error from stream: Secure connection setup failed. (gstsouphttpsrc.c(1578): gst_soup_http_src_parse_status (): /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0/GstSoupHTTPSrc:source:
Unacceptable TLS certificate (6), URL: https://192.168.0.46/nextcloud/apps/music/ampache/server/xml.server.php?action=play&filter=1&auth=47749254abba0ec16b4907080e8e3bb8, Redirect to: (NULL))`
`(08:27:38) [0x7f0d38005840] [track_change_done] rb-player-gst.c:359: track change failed: Secure connection setup failed.`
`(08:27:38) [0x7f0d38005840] [rb_shell_player_error] rb-shell-player.c:2443: playback error while playing: Secure connection setup failed.`
`(08:27:38) [0x7f0d38005840] [error_cb] rb-shell-player.c:2547: exiting error hander
`

This sounds like it might be related to a similar subsonic issue https://github.com/clementine-player/Clementine/issues/5360. 

I am using a self-signed cert, so perhaps the RB plugin needs an option for the user to add an exception for self-signed certs? Or maybe it's an unrelated issue... Any help appreciated!

**Comment by lotan** [comment]
Did you try opening ```https://192.168.0.46/nextcloud/apps/music/ampache/server/xml.server.php?action=play&filter=1&auth=47749254abba0ec16b4907080e8e3bb8``` in a browser?
I suspect it works.

I've had similar problems once using a self-signed certificate. Refer to ```https://developer.gnome.org/libsoup/stable/SoupSession.html#SoupSession--ssl-strict``` for more information.

I tried patching rhythmbox to set property ssl-strict to false, but that wasn't sustainable. Every new version would have to recompiled.

Then I added my ca certificate to my clients - also cumbersome.

Now my server has a letsencrypt certificate and I have no problem of the sort anymore.

I hope that helps.

**Comment by jlombs** [comment]
Good info! I followed your lead and just upgraded to a letsencrypt cert, which fixed the problem as expected. This was a two-for-one fix for me, because this turned out to also be the same issue behind getting an ampache android app to work for me. So bonus points!

Cheers

**Comment by lotan** [comment]
I'm glad that helped you, too!

**Comment by crvigh** [comment]
Did you consider submitting the plugin to upstream rhythmbox ? That way it would reach more users.

https://gitlab.gnome.org/GNOME/rhythmbox/-/merge_requests

Thanks !

**Comment by crvigh** [comment]
Seems like this is already handled in Grilo plugin.

https://gitlab.gnome.org/GNOME/grilo-plugins/-/issues/26
