### ISSUE TITLE
The plugin must be installed in /usr/lib64 for 64 bits systems

### ISSUE THREAD

**Issue by jorti** [lotan/rhythmbox-ampache#2]
in setup.py line 24, the plugin is always installed in /usr/lib, but if we are installing in a 64 bit OS, the correct folder is /usr/lib64.

**Comment by lotan** [comment]
Hi jorti,
I hadn't thought about that issue as in both distributions I use, ```/usr/lib``` is a link to ```/usr/lib64```.

My first instinct was to admit you're right and find a good way to change the installation procedure.

However, when I read up on the issue, it seems that if the code is platform independent i.e. there is no platform dependent library, the correct path is ```/usr/lib```.
```distutils.sysconfig.get_python_lib``` returns ```/usr/lib``` for non platform specific code even on Red Hat flavoured distributions.

As the search path contains ```/usr/lib``` (see the following at the bottom):
```
Python 2.6.6 (r266:84292, Nov 22 2013, 12:16:22) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> for pth in sys.path: print pth
... 

/usr/lib64/python26.zip
/usr/lib64/python2.6
/usr/lib64/python2.6/plat-linux2
/usr/lib64/python2.6/lib-tk
/usr/lib64/python2.6/lib-old
/usr/lib64/python2.6/lib-dynload
/usr/lib64/python2.6/site-packages
/usr/lib64/python2.6/site-packages/gst-0.10
/usr/lib64/python2.6/site-packages/gtk-2.0
/usr/lib64/python2.6/site-packages/webkit-1.0
/usr/lib/python2.6/site-packages
```
I think this should be fine.

So unless I've understood it wrong, I'll leave the installation procedure for now.

**Comment by jorti** [comment]
Excuse me if I haven't explained it right. I'm talking about the location of these files:
```
data_files=[
          ("lib/rhythmbox/plugins/ampache", ["ampache.plugin", "ampache.py", "AmpacheBrowser.py", "AmpacheConfigDialog.py"]),
```

In my Fedora x86_64 box, all other plugins are installed at /usr/lib64/rhythmbox/plugins, and they are a mix of python code and arch-specific code. I'm not an expert, but I guess you could get that information with something like:
```
Python 2.7.9 (default, Apr 15 2015, 12:08:00) 
[GCC 5.0.0 20150319 (Red Hat 5.0.0-0.21)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from distutils.sysconfig import get_config_var
>>> get_config_var('LIBDIR')
'/usr/lib64'
```

**Comment by lotan** [comment]
No, that's my fault.
You're absolutely right. This is not a python module but a rhythmbox plugin.
I must have some kind of brain freeze.
I've changed ```setup.py``` now.
I'd be grateful for a test.

**Comment by jorti** [comment]
Thanks, it works.

**Comment by lotan** [comment]
Thank you for getting back to me.
