### ISSUE TITLE
Make optional the glib-compile-schemas step at installation

### ISSUE THREAD

**Issue by jorti** [lotan/rhythmbox-ampache#3]
I'm creating a rpm package for this plugin [1], and I'm commenting out the glib-compile-schemas step because I do it from the rpm, it would be great to make this step optional.

[1] https://jorti.fedorapeople.org/rhythmbox-ampache/rhythmbox-ampache-0-0.1.20150518git7c1d978.fc22.src.rpm

**Comment by lotan** [comment]
Introduced ```--no-glib-compile-schemas``` argument to ```setup.py install```, see https://github.com/lotan/rhythmbox-ampache/blob/master/setup.py#L27, which should hopefully do the trick for you.

**Comment by jorti** [comment]
That's perfect, thank you.

I've submitted the package for inclusion in Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1222484

**Comment by lotan** [comment]
Great, thanks for the feedback!
