### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by jorti** [lotan/rhythmbox-ampache#4]
The GPLv2 license is included, but it is not specified anywhere under which license the source code is, or if it is under the GPLv2 or (at your option) any later version.

Quoting from gnu.org:
> Whichever license you plan to use, the process involves adding two elements to each source file of your program: a copyright notice (such as “Copyright 1999 Terry Jones”), and a statement of copying permission, saying that the program is distributed under the terms of the GNU General Public License (or the Lesser GPL).

https://www.gnu.org/licenses/gpl-howto.en.html

**Comment by lotan** [comment]
Thanks for that hint. I added that copyright notice.
