### ISSUE TITLE
g-io-error-quark: HTTP Error: Internal Server Error

### ISSUE THREAD

**Issue by qirtaiba** [lotan/rhythmbox-ampache#5]
I get this error on the console when using the plugin with ownCloud's Ampache API:

    (19:31:04) [0x1eda940] [AmpacheBrowser.handshake_cb] ampache/AmpacheBrowser.py:1151: downloading playlists: http://www.malcolm.id.au/owncloud/index.php/apps/music/ampache/server/xml.server.php?action=playlists&auth=***removed***
    (19:31:05) [0x1eda940] [AmpacheBrowser.download_iterate] ampache/AmpacheBrowser.py:701: process playlist: _songs
    (19:31:05) [0x1eda940] [AmpacheBrowser.download_songs_chunk] ampache/AmpacheBrowser.py:664: downloading songs: http://www.malcolm.id.au/owncloud/index.php/apps/music/ampache/server/xml.server.php?action=songs&auth=***removed***&offset=0&limit=5000

It is followed by this error in a dialog:

    Songs response: g-io-error-quark: HTTP Error: Internal Server Error (0)

**Comment by lotan** [comment]
The HTTP error message "Internal Server Error" is a generic error message, given when an unexpected condition was encountered and no more specific message is suitable.
I think your best bet is to check the log files of your HTTP server after issuing the Ampache request.

**Comment by qirtaiba** [comment]
The HTTP log is not very illuminating. It's just this:

    192.168.42.113 - - [09/Feb/2016:19:13:58 -0800] "GET /owncloud/index.php/apps/music/ampache/server/xml.server.php/server/xml.server.php?action=handshake&auth=***removed***&timestamp=1455074038&user=terminus&version=350001 HTTP/1.1" 200 10838 "-" "gvfs/1.22.2"

Followed by a whole lot of lines like this:

    192.168.42.113 - terminus [09/Feb/2016:19:14:07 -0800] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 1519 "-" "Mozilla/5.0 (Linux) mirall/2.0.2"
    192.168.42.113 - terminus [09/Feb/2016:19:14:10 -0800] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 369 "-" "Mozilla/5.0 (Linux) mirall/2.0.2"

**Comment by lotan** [comment]
The log's indeed not very talkative.

From what I understand, ```PROPFIND``` is a WebDAV HTTP extension which we don't want to see in Ampache communication anyway. Something seems wrong to me.

Can you enter the URIs - or at least the first of them - manually in a browser in order to find out whether ampache is indeed on the other side?

$HOST/owncloud/index.php/apps/music/ampache/server/xml.server.php?action=handshake&auth=***removed***&timestamp=1455075058&user=terminus&version=350001

**Comment by qirtaiba** [comment]
Just says

    Invalid Login - session is outdated

Yeah I think those WebDAV lines are a red herring. The same client also does general file synchronisation, separate from the music. So that's probably the explanation for those.
