### ISSUE TITLE
Plugin non functional on debian jessie with rhytmbox 3.1

### ISSUE THREAD

**Issue by autious** [lotan/rhythmbox-ampache#8]
Installed using setup.py script, plugin doesn't appear on the plugin list and no references to amapache is mentioned in the output of rhytmbox.

**Comment by autious** [comment]
I'll look more into the problem later and see if i can suggest a fix.

**Comment by lotan** [comment]
Ok.
Maybe you could run ```setup.py install``` again and post ist here.

**Comment by autious** [comment]
Yes, ofcourse, sorry, made this as a placeholder for later, but this would have been minimal work. 

`running install
running build
running install_data
warning: undefined reference to <schema id='org.gnome.rhythmbox.source'/>
running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/rhythmbox_ampache-0.11.egg-info
Writing /usr/local/lib/python2.7/dist-packages/rhythmbox_ampache-0.11.egg-info`

**Comment by breaker1** [comment]
@autious Just a guess, but you should try installing in /usr and not /usr/local . I'm running Arch here, but that's where I would expect debian to be looking as well.

**Comment by autious** [comment]
That wouldn't follow the guidelines for how to install software on the debian platform though. But i get what you're saying, rhytmbox is probably looking the wrong place.

**Comment by lotan** [comment]
I agree with @breaker1, @autious.
The plugin will have to be installed in /usr/lib rather than /usr/local/lib.
In my last comment in issue #1 I described that you can set the prefix using the ```--prefix``` argument.
Set that to user and it'll probably work.

**Comment by Jamie-uni** [comment]
I had the same issue as @autious, but using `python setup.py install --prefix /usr --exec-prefix /usr` successfully installed on debian.

**Comment by lotan** [comment]
Thanks for your feedback. Closing...
